"""Customer payment receipt email — additive, idempotent, best-effort.

Sends a professional CloudPay-branded HTML receipt to the customer when a payment first
reaches a final successful state (succeeded / captured). Reuses the existing provider-agnostic
`email_service` (Resend when configured, noop otherwise). Never raises and never aborts the
payment/ledger transaction; idempotent via a `receipt_sent_at` marker in payment metadata so
webhook replays and operation retries never send a duplicate.
"""
import logging
from datetime import datetime, timezone

from sqlalchemy import select

from app.core.config import settings
from app.core.security import generate_token
from app.models.payment import Payment
from app.models.tenant import Tenant
from app.services import email_service

logger = logging.getLogger("cloudpay.receipt")

# Final, customer-facing success states that warrant a receipt.
FINAL_SUCCESS_STATES = {"succeeded", "captured"}


def _format_amount(amount_minor: int, currency: str) -> str:
    return f"{(amount_minor or 0) / 100:,.2f} {currency}"


def _row(label: str, value: str) -> str:
    return (
        '<tr>'
        f'<td style="padding:10px 0;color:#6b7280;font-size:13px">{label}</td>'
        f'<td style="padding:10px 0;color:#111827;font-size:13px;font-weight:600;'
        f'text-align:right">{value}</td>'
        '</tr>'
    )


def _build_html(*, reference, amount_str, status, provider_txn, when, tenant_name, support_email,
                receipt_url=None) -> str:
    support_block = ""
    if support_email:
        support_block = (
            '<p style="margin:20px 0 0;color:#6b7280;font-size:12px;line-height:1.6">'
            f'Questions about this payment? Contact {tenant_name} at '
            f'<a href="mailto:{support_email}" style="color:#4f46e5;text-decoration:none">'
            f'{support_email}</a>.</p>'
        )
    button_block = ""
    if receipt_url:
        button_block = (
            f'<a href="{receipt_url}" style="display:inline-block;background:#4f46e5;color:#ffffff;'
            'text-decoration:none;font-size:13px;font-weight:600;padding:11px 20px;border-radius:8px;'
            'margin:4px 0 20px">View receipt</a>'
        )
    rows = "".join([
        _row("Reference", reference),
        _row("Amount", amount_str),
        _row("Status", status.capitalize()),
        _row("Provider transaction", provider_txn or "—"),
        _row("Date &amp; time", when),
        _row("Merchant", tenant_name),
    ])
    return (
        '<div style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif">'
        '<div style="max-width:520px;margin:0 auto;padding:32px 20px">'
        '<div style="background:#111827;border-radius:12px 12px 0 0;padding:24px 28px">'
        '<div style="color:#ffffff;font-size:20px;font-weight:700;letter-spacing:-0.02em">CloudPay</div>'
        '<div style="color:#9ca3af;font-size:12px;margin-top:2px">Payment receipt</div>'
        '</div>'
        '<div style="background:#ffffff;border-radius:0 0 12px 12px;padding:28px;'
        'box-shadow:0 1px 3px rgba(0,0,0,0.08)">'
        '<div style="display:inline-block;background:#ecfdf5;color:#047857;font-size:12px;'
        'font-weight:600;padding:6px 12px;border-radius:9999px;margin-bottom:8px">'
        'Payment successful</div>'
        f'<h1 style="margin:8px 0 4px;color:#111827;font-size:26px;font-weight:700">{amount_str}</h1>'
        f'<p style="margin:0 0 20px;color:#6b7280;font-size:13px">Thank you for your payment to {tenant_name}.</p>'
        f'{button_block}'
        '<table style="width:100%;border-collapse:collapse;border-top:1px solid #f3f4f6">'
        f'{rows}'
        '</table>'
        f'{support_block}'
        '<hr style="border:none;border-top:1px solid #f3f4f6;margin:24px 0">'
        '<div style="color:#9ca3af;font-size:11px;line-height:1.6">'
        'This receipt was generated by CloudPay. Sandbox environment. '
        'Please keep it for your records.</div>'
        '</div></div></div>'
    )


def _build_text(*, reference, amount_str, status, provider_txn, when, tenant_name, support_email,
                receipt_url=None) -> str:
    lines = [
        f"Payment successful — {amount_str}",
        f"Thank you for your payment to {tenant_name}.",
        "",
        f"Reference: {reference}",
        f"Amount: {amount_str}",
        f"Status: {status.capitalize()}",
        f"Provider transaction: {provider_txn or '—'}",
        f"Date & time: {when}",
        f"Merchant: {tenant_name}",
    ]
    if receipt_url:
        lines += ["", f"View / print your receipt: {receipt_url}"]
    if support_email:
        lines += ["", f"Questions? Contact {tenant_name} at {support_email}."]
    return "\n".join(lines)


async def send_payment_receipt(db, *, payment: Payment) -> dict | None:
    """Best-effort idempotent customer receipt. Returns the send result or None; never raises."""
    try:
        if payment.status not in FINAL_SUCCESS_STATES:
            return None
        if not payment.customer_email:
            return None
        md = dict(payment.metadata_json or {})
        if md.get("receipt_sent_at"):
            return None

        tenant = (await db.execute(
            select(Tenant).where(Tenant.id == payment.tenant_id))).scalar_one_or_none()
        tenant_name = (tenant.name if tenant and tenant.name else "CloudPay")
        support_email = tenant.contact_email if tenant else None

        when = (payment.created_at or datetime.now(timezone.utc)).strftime("%d %b %Y, %H:%M UTC")
        amount_str = _format_amount(payment.amount_minor, payment.currency)
        # A non-enumerable hosted-receipt token so the customer (and operators) can open a
        # printable copy. Persisted only when the send is not a transient failure.
        token = md.get("receipt_token") or generate_token(24)
        receipt_url = f"{settings.frontend_url.rstrip('/')}/receipt/{token}"
        fields = dict(reference=payment.reference, amount_str=amount_str, status=payment.status,
                      provider_txn=payment.provider_txn_id, when=when, tenant_name=tenant_name,
                      support_email=support_email, receipt_url=receipt_url)

        result = email_service.send_email(
            to=payment.customer_email,
            subject=f"Your {tenant_name} payment receipt — {payment.reference}",
            body=_build_text(**fields),
            html=_build_html(**fields),
        )

        # Mark as sent unless the send transiently failed (so a retry can re-attempt).
        if result.get("status") != "send_failed":
            md["receipt_sent_at"] = datetime.now(timezone.utc).isoformat()
            md["receipt_status"] = result.get("status")
            md["receipt_token"] = token
            payment.metadata_json = md
        return result
    except Exception as exc:  # pragma: no cover - defensive; never break the payment flow
        logger.error("payment receipt send failed payment=%s error=%s",
                     getattr(payment, "id", None), exc)
        return None
