"""auth security: mfa, reset tokens, sessions, login history

Revision ID: c1e050d6bc48
Revises: fa05f65c8ea5
Create Date: 2026-09-01 11:33:31.621274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1e050d6bc48'
down_revision: Union[str, None] = 'fa05f65c8ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_email'), 'login_history', ['email'], unique=False)
    op.create_index(op.f('ix_login_history_tenant_id'), 'login_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('security_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_tokens_token_hash'), 'security_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_security_tokens_user_id'), 'security_tokens', ['user_id'], unique=False)
    op.add_column('auth_sessions', sa.Column('kind', sa.String(length=20), nullable=False, server_default='google'))
    op.add_column('auth_sessions', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('auth_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('auth_sessions', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'token_version')
    op.drop_column('auth_sessions', 'last_seen_at')
    op.drop_column('auth_sessions', 'revoked_at')
    op.drop_column('auth_sessions', 'ip_address')
    op.drop_column('auth_sessions', 'kind')
    op.drop_index(op.f('ix_security_tokens_user_id'), table_name='security_tokens')
    op.drop_index(op.f('ix_security_tokens_token_hash'), table_name='security_tokens')
    op.drop_table('security_tokens')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_tenant_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_email'), table_name='login_history')
    op.drop_table('login_history')
    # ### end Alembic commands ###
