"""branding, webhook retries, scheduled reports

Revision ID: fa05f65c8ea5
Revises: 87bb7ea5148a
Create Date: 2026-09-01 10:47:20.986277
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa05f65c8ea5'
down_revision: Union[str, None] = '87bb7ea5148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_files_tenant_id'), 'stored_files', ['tenant_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=30), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('settlements_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reports_tenant_id'), 'scheduled_reports', ['tenant_id'], unique=False)
    op.create_index('ix_scheduled_reports_tenant_period', 'scheduled_reports', ['tenant_id', 'period_date'], unique=False)
    op.add_column('tenants', sa.Column('brand_accent', sa.String(length=9), nullable=False, server_default='#3B82F6'))
    op.add_column('tenants', sa.Column('brand_logo_file_id', sa.UUID(), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('event_id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.add_column('webhook_deliveries', sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='8'))
    op.add_column('webhook_deliveries', sa.Column('retryable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('webhook_deliveries', sa.Column('is_replay', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('webhook_deliveries', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_next_attempt_at'), 'webhook_deliveries', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_next_attempt_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_column('webhook_deliveries', 'next_attempt_at')
    op.drop_column('webhook_deliveries', 'last_attempt_at')
    op.drop_column('webhook_deliveries', 'is_replay')
    op.drop_column('webhook_deliveries', 'retryable')
    op.drop_column('webhook_deliveries', 'max_attempts')
    op.drop_column('webhook_deliveries', 'event_id')
    op.drop_column('tenants', 'brand_logo_file_id')
    op.drop_column('tenants', 'brand_accent')
    op.drop_index('ix_scheduled_reports_tenant_period', table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_tenant_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_stored_files_tenant_id'), table_name='stored_files')
    op.drop_table('stored_files')
    # ### end Alembic commands ###
